[package]
edition = "2021"
license = "MIT"
name = "rs-2048"
version = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = {version = "0.26.1"}
fltk = "1.4.6"
tinyrand = "0.5.0"

# https://github.com/johnthagen/min-sized-rust
[profile.release]
codegen-units = 1 
lto = true 
opt-level = "z" # Optimize for size.
panic = "abort" 
strip = true
