name: Clippy check

on:
  push:
  workflow_dispatch:

env:
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: cargo fmt --check --all --verbose
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
